routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Controllers
use App\Http\Controllers\PagesController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BalanceBoxController;
use App\Http\Controllers\DaganganController;
use App\Http\Controllers\Profil\ProfilController;
use App\Http\Controllers\Profil\DagangankuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class, 'beranda'])->name('beranda');
Route::get('/tentang', [PagesController::class, 'tentang'])->name('tentang');

// Auth
Route::get('/masuk', [AuthController::class, 'masuk'])->middleware('guest')->name('masuk');
Route::get('/daftar', [AuthController::class, 'daftar'])->middleware('guest')->name('daftar');

Route::post('/daftar', [AuthController::class, 'prosesDaftar'])->name('prosesDaftar');
Route::post('/masuk', [AuthController::class, 'prosesMasuk'])->name('prosesMasuk');

// Profile
Route::middleware(['cek.auth'])->prefix('profil')->group(function () {
    Route::get('/', [ProfilController::class, 'index'])->name('profil');
    Route::patch('/', [ProfilController::class, 'simpanProfil'])->name('simpanProfil');

    // Products
    Route::get('/daganganku', [DagangankuController::class, 'index'])->name('daganganku');
    Route::get('/daganganku/tambah', [DagangankuController::class, 'tambahProduk'])->name('tambahProduk');
    Route::get('/daganganku/{id}/ubah', [DagangankuController::class, 'ubahProduk'])->name('ubahProduk');

    Route::post('/daganganku/tambah', [DagangankuController::class, 'prosesTambahProduk'])->name('prosesTambahProduk');
    Route::patch('/daganganku/{id}', [DagangankuController::class, 'prosesUbahProduk'])->name('prosesUbahProduk');
    Route::delete('/daganganku/{id}', [DagangankuController::class, 'prosesHapusProduk'])->name('prosesHapusProduk');


    Route::get('/keluar', [AuthController::class, 'keluar'])->name('keluar');
});

// Dagangan
Route::prefix('dagangan')->group(function () {
    Route::get('/', [DaganganController::class, 'index'])->name('dagangan');
    Route::get('/{slug}', [DaganganController::class, 'detail'])->name('detailDagangan');

    Route::middleware(['cek.auth'])->get('/{slug}/beli', [DaganganController::class, 'beli'])->name('beliDagangan');
    Route::middleware(['cek.auth'])->post('/{id}/beli', [DaganganController::class, 'prosesBeliDagangan'])->name('prosesBeliDagangan');
});

// Balance Box
Route::middleware(['cek.auth'])->get('balance-box', [BalanceBoxController::class, 'index'])->name('balanceBox');
Route::middleware(['cek.auth'])->post('balance-box', [BalanceBoxController::class, 'deposit'])->name('balanceBoxDeposit');
Route::middleware(['cek.auth'])->delete('balance-box', [BalanceBoxController::class, 'withdraw'])->name('balanceBoxWithdraw');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Student extends Authenticatable
{
    use HasFactory;
    protected $primaryKey = "student_id";
    public $incrementing = false;

    protected $fillable = [
        'student_id',
        'name',
        'password',
    ];

    protected $hidden = [
        'password',
    ];

    // Canteen Balance Box
    public function CanteenBalanceBox()
    {
        return CanteenBalanceBox::where('id', 1)->first();
    }

    public function getCanteenBalanceBoxAttribute()
    {
        return rupiah($this->CanteenBalanceBox()->amount ?? 0);
    }
}

resources/views/layout/app.blade.php
@include('layout.header')

<body class="bg-gray-100">
    <main class="font-be-vietnam text-gray-800 h-auto px-4 mx-auto max-w-screen-xl lg:px-24 bg-white min-h-screen">
        @include('layout.navbar')
        @yield('content')
        @include('layout.footer')
    </main>
</body>

</html>

resources/views/layout/footer.blade.php
<footer class="lg:text-left text-gray-600 py-10">
    <div class="inline-flex justify-start items-center w-full text-gray-700">
        <span>Dibuat dengan</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="mx-1 h-5 w-5 text-red-500" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd"
                d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                clip-rule="evenodd" />
        </svg>
        <span>oleh</span>
        <a class="ml-1 text-gray-600 font-semibold" target="_blank" href="https://rafipriatna.id/">Rafi Priatna K</a>.
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    // Navbar toggling animation           
    $(document).ready(function() {
        $(".mobile-menu-button").each(function(_, navToggler) {
            var target = $(navToggler).data("target");
            $(navToggler).on("click", function() {
                $(target).animate({
                    height: "toggle",
                })
            })
        })
    })
</script>
@yield('js')

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') | KantinKejujuran</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.0/dist/alpine.min.js" defer></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Addon CSS -->
    @yield('css')
    
</head>

resources/views/layout/navbar.blade.php
<nav class="lg:pt-7 pt-5 z-50">
    <div class="flex flex-col w-full lg:flex-row lg:items-center gap-5 divide-gray-700 lg:divide-x">
        <div class="flex items-center justify-between flex-none">
            <!-- LOGO -->
            <div class="text-xl font-bold">KJ</div>
            <!-- RESPONSIVE NAVBAR BUTTON TOGGLER -->
            <div>
                <button class="block p-1 outline-none lg:hidden mobile-menu-button" data-target="#navigation">
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-7 h-7" x-show="!showMenu" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8h16M4 16h16">
                        </path>
                        <path stroke-linecap="round" class="hidden w-7 h-7" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
        <div class="flex hidden w-full mx-auto mobile-menu lg:block" id="navigation">
            <div class="flex flex-col items-baseline justify-between mx-auto mt-6 lg:flex-row lg:items-center lg:mt-0">
                <div class="flex flex-col w-full text-base font-normal lg:flex-row lg:w-max lg:pl-4">
                    <a href="{{ route('beranda') }}"
                        class="py-3 px-4 mx-2 hover:text-champ-green {{ Request::is('/') ? 'font-bold text-champ-green' : '' }}">Beranda</a>
                    <a href="{{ route('tentang') }}"
                        class="py-3 px-4 mx-2 hover:text-champ-green {{ Request::is('tentang') ? 'font-bold text-champ-green' : '' }}">Tentang</a>
                    <a href="{{ route('dagangan') }}"
                        class="py-3 px-4 mx-2 hover:text-champ-green {{ Request::is('dagangan') ? 'font-bold text-champ-green' : '' }}">Dagangan</a>
                </div>
                <div
                    class="flex flex-col lg:flex-row inline-flex gap-4 lg:gap-7 w-full px-3 mt-4 lg:mt-0 lg:w-max lg:px-0">
                    @if (!Auth::check())
                        <a href="{{ route('masuk') }}"
                            class="w-full lg:w-auto px-5 py-3 text-center rounded-lg flex lg:mx-auto transition ease-out duration-200 hover:bg-champ-green hover:bg-opacity-80 hover:text-white">
                            <span class="text-base w-full font-semibold">Masuk</span>
                        </a>
                        <a href="{{ route('daftar') }}"
                            class="w-full lg:w-auto px-5 py-3 text-center rounded-lg flex bg-champ-green lg:mx-auto bg-champ-green transition ease-out duration-200 hover:bg-opacity-80">
                            <span class="text-base w-full font-semibold text-white">Daftar</span>
                        </a>
                    @else
                        <div x-data="{ dropdownMenu: false }" class="relative">
                            <!-- Dropdown toggle button -->
                            <button type="button" @click="dropdownMenu = !dropdownMenu"
                                @click.away="dropdownMenu = false"
                                class="ml-3 inline-flex items-center w-full text-gray-700 font-semibold">
                                Halo, {{ Auth()->user()->name }}
                                <template x-if="!dropdownMenu">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="-mr-1 ml-2 h-5 w-5" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                                    </svg>
                                    </svg>
                                </template>
                                <template x-if="dropdownMenu">
                                    <svg x-if="dropdownMenu == false" xmlns="http://www.w3.org/2000/svg"
                                        class="-mr-1 ml-2 h-5 w-5" fill="none" viewBox="0 0 24 24"
                                        stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
                                    </svg>
                                </template>
                            </button>
                            <!-- Dropdown list -->
                            <div x-show="dropdownMenu"
                                class="absolute right-0 py-2 mt-2 bg-white bg-gray-100 rounded-md shadow-xl w-44 z-50">
                                <div class="block px-4 py-2 text-sm text-champ-green">
                                    Balance Box:
                                    <span class="block">
                                        {{ Auth::user()->canteen_balance_box }}
                                    </span>
                                </div>
                                <hr>
                                <a href="{{ route('balanceBox') }}"
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-champ-green hover:text-white">
                                    Balance Box
                                </a>
                                <a href="{{ route('profil') }}"
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-champ-green hover:text-white">
                                    Profil
                                </a>
                                <a href="{{ route('daganganku') }}"
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-champ-green hover:text-white">
                                    Daganganku
                                </a>
                                <a href="{{ route('keluar') }}"
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-champ-green hover:text-white">
                                    Keluar
                                </a>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</nav>